# Generated by Django 6.0.7 on 2026-08-14 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreverse', '0005_readingprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
