# Generated by Django 6.0.7 on 2026-08-14 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreverse', '0006_story_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='want_to_read_by',
            field=models.ManyToManyField(blank=True, related_name='want_to_read_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
