# Generated by Django 6.0.7 on 2026-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreverse', '0009_completedstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Science Fiction', 'Science Fiction'), ('Adventure', 'Adventure'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
