# Generated by Django 6.0.7 on 2026-08-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreverse', '0010_story_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
