# Generated by Django 6.0.7 on 2026-08-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreverse', '0011_story_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world', to='loreverse.story')),
            ],
        ),
    ]
