# Generated by Django 6.0.7 on 2026-08-14 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreverse', '0013_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='loreverse.world')),
            ],
        ),
    ]
