# Generated by Django 6.0.7 on 2026-08-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreverse', '0015_creature'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(max_length=100)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='loreverse.world')),
            ],
        ),
    ]
