# Generated by Django 6.0.7 on 2026-08-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreverse', '0016_timelineevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='description',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='character_images/')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loreverse.character')),
            ],
        ),
        migrations.CreateModel(
            name='CreatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='creature_images/')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loreverse.creature')),
            ],
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location_images/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loreverse.location')),
            ],
        ),
        migrations.CreateModel(
            name='WorldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='world_images/')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loreverse.world')),
            ],
        ),
    ]
