# Generated by Django 6.0.7 on 2026-08-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreverse', '0019_chaptercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='story_covers/'),
        ),
    ]
