from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile_view, name="profile"),
    path("reader-dashboard/", views.reader_dashboard, name="reader_dashboard"),
    path("become_writer/", views.become_writer, name="become_writer"),
    path("change_password/", views.change_password_view, name="change_password"),
    path("create_story/", views.create_story, name="create_story"),
    path("my_stories/", views.my_stories, name="my_stories"),
    path("edit_story/<int:story_id>/", views.edit_story, name="edit_story"),
    path("delete_story/<int:story_id>/", views.delete_story, name="delete_story"),
    path("publish_story/<int:story_id>/", views.publish_story, name="publish_story"),
    path("stories/<int:story_id>/create_world/", views.create_world, name="create_world"),
    path("stories/<int:story_id>/world/", views.world_explorer, name="world_explorer"), 
    path("stories/<int:story_id>/world/character/add/", views.create_character, name="create_character"),
    path("stories/<int:story_id>/world/location/add/", views.create_location, name="create_location"),
    path("stories/<int:story_id>/world/creature/add/", views.create_creature, name="create_creature"),
    path("stories/<int:story_id>/world/timeline/add/", views.create_timeline_event, name="create_timeline_event"),
    path("stories/", views.published_stories, name="published_stories"),
    path("stories/<int:story_id>/", views.story_detail, name="story_detail"),
    path("stories/<int:story_id>/favorite/", views.toggle_favorite, name="toggle_favorite"),
    path("stories/<int:story_id>/want-to-read/", views.toggle_want_to_read, name="toggle_want_to_read"),
    path("stories/<int:story_id>/completed/", views.toggle_completed, name="toggle_completed"),
    path("stories/<int:story_id>/chapter/<int:chapter_id>/", views.read_chapter, name="read_chapter"),
    path("stories/<int:story_id>/chapters/<int:chapter_id>/like/",views.toggle_chapter_like, name="toggle_chapter_like"),
    path("stories/<int:story_id>/continue/", views.continue_reading, name="continue_reading"),
    path("stories/<int:story_id>/create_chapter/", views.create_chapter, name="create_chapter"),
    path("stories/<int:story_id>/world/image/add/", views.add_world_image, name="add_world_image"),
    path("stories/<int:story_id>/world/character/<int:character_id>/image/add/",views.add_character_image,name="add_character_image"),
    path("stories/<int:story_id>/world/location/<int:location_id>/image/add/", views.add_location_image, name="add_location_image"),
    path("stories/<int:story_id>/world/creature/<int:creature_id>/image/add/",views.add_creature_image,name="add_creature_image"),
]